server:
  port: 8081

spring:
  application:
    name: arenita-tracking
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:arenita_tracking;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/arenita_tracking
    driver-class-name: org.postgresql.Driver
    username: arenita
    password: arenita_secret
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.arenita: INFO
